version: "3.9"
services:
  discordbot:
    build: .
    restart: unless-stopped
    env_file:
     - CONFIG.env
    volumes:
     - ./server_config.db:/config.db
    depends_on:
     - redisserver
  redisserver:
    image: redis:6.2.1-buster
    restart: unless-stopped
  web:
    build: webserver/
    restart: unless-stopped
    depends_on:
     - redisserver
    ports:
     - "127.0.0.1:8731:8000"
