version: "3.9"
services:
  discordbot:
    build: .
    restart: unless-stopped
    env_file:
     - CONFIG.env
    volumes:
     - ./server_config.db:/config.db
    depends_on:
     - redis
  redis:
    image: redis:6.2.1-alpine
    restart: unless-stopped
  web:
    build: webserver/
    restart: unless-stopped
    depends_on:
     - redis
